server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/productdb
    username: root
    password: Sai@123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296


management:
  tracing:
    sampling:
      probability: 1.0 # trace 100% of requests (important for testing)
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # send spans to Zipkin
  endpoints:
    web:
      exposure:
        include: health, prometheus
  endpoint:
    prometheus:
      enabled: true

logging:
  level:
    root: info
    io.micrometer.tracing: DEBUG
    io.zipkin.reporter2: DEBUG

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    level: "%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]"
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: https://dev-nnxp3ymqgxzv0l4s.us.auth0.com/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

